# Generated by Django 3.0.5 on 2021-07-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
