# Generated by Django 3.0.5 on 2022-02-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_auto_20210730_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='otherShift',
            field=models.BooleanField(default=False),
        ),
    ]
