# Generated by Django 3.0.5 on 2022-02-28 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_shift_othershift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='otherShift',
            new_name='other_shift',
        ),
    ]
