# Generated by Django 3.0.5 on 2022-02-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_auto_20220228_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='other_shift',
        ),
    ]
