# Generated by Django 3.0.5 on 2022-02-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_remove_shift_other_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='other_shift',
            field=models.BooleanField(default=False),
        ),
    ]
