# Generated by Django 3.0.5 on 2021-06-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiology',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Doctor'),
        ),
        migrations.AddField(
            model_name='examination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Patient'),
        ),
        migrations.AddField(
            model_name='examination',
            name='radiology',
            field=models.ManyToManyField(to='radiology.Radiology'),
        ),
        migrations.AddField(
            model_name='examination',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Doctor'),
        ),
    ]
