# Generated by Django 3.0.5 on 2021-06-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_auto_20210624_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
