# Generated by Django 3.2.4 on 2021-06-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_examination_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='notes',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='radiology',
            name='notes',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='examination',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
        ),
    ]
