# Generated by Django 3.2.4 on 2021-06-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0003_auto_20210608_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiology',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
