# Generated by Django 3.0.5 on 2021-07-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0003_auto_20210626_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiology',
            name='doctor',
        ),
    ]
