# Generated by Django 3.2.4 on 2021-06-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0004_auto_20210608_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='radiology',
            field=models.ManyToManyField(to='radiology.Radiology'),
        ),
        migrations.AlterField(
            model_name='radiology',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
        ),
    ]
