# Generated by Django 3.2.4 on 2021-06-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0005_auto_20210608_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiology',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
