# Generated by Django 3.0.5 on 2021-07-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0005_auto_20210727_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='another_supervisor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
