# Generated by Django 3.0.5 on 2021-07-30 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        ('radiology', '0006_examination_another_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='shift_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shifts.Shift'),
        ),
    ]
