# Generated by Django 3.0.5 on 2021-07-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
        ('radiology', '0008_auto_20210730_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.Insurance'),
        ),
    ]
