# Generated by Django 3.0.5 on 2021-06-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('user', '0002_auto_20210624_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blood_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.BloodType'),
        ),
    ]
