# Generated by Django 3.2.4 on 2021-06-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_receptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='address',
            field=models.TextField(),
        ),
    ]
