# Generated by Django 3.0.5 on 2021-06-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210624_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('R', 'Receptionist'), ('D', 'Doctor'), ('P', 'Patient'), ('A', 'Admin')], default='R', max_length=1),
        ),
    ]
