# Generated by Django 3.2.4 on 2021-06-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtype',
            name='notes',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='department',
            name='notes',
            field=models.TextField(default=' '),
        ),
    ]
